#######################################################################
#                           ShyParticles                             #
#                            by Shynixn                              #
#######################################################################

############################
# Language settings
############################
language: "en_us"

############################
# Command settings
############################
commands:
  shyparticles:
    aliases:
      - "sparticles"
      - "sp"

############################
# Particle Engine Settings
############################
engine:
  # Maximum number of particles that can be displayed at once per effect
  maxParticlesPerEffect: 1000
  
  # Maximum number of concurrent effects per player
  maxEffectsPerPlayer: 5
  
  # Maximum number of concurrent effects globally
  maxGlobalEffects: 50
  
  # Update frequency in ticks (20 ticks = 1 second)
  updateFrequency: 1
  
  # Maximum render distance for particles
  renderDistance: 64.0

############################
# Performance Settings
############################
performance:
  # Automatically reduce particle density when TPS is low
  adaptivePerformance: true
  
  # TPS threshold below which particles are reduced
  tpsThreshold: 18.0
  
  # Particle reduction factor when TPS is low (0.5 = 50% particles)
  reductionFactor: 0.5